### PR TITLE
Use custom MemoryLeakError

### LINKED ISSUE #10: Custom Error
this https://github.com/andywer/leakage/blob/master/lib/leakErrorFactory.js#L26 should use a custom error

The custom Error should be exported as well so we can do that:
```js
import { iterate, LeakageError } from 'leakage';

try {
  iterate(100, () => {
    throw new Error('random error')
  })
} catch (err) {
  if (err instanceof LeakageError) {
    // leaked detected
  }

  // something else happened
}
```

-------

I use `LeakageError` but we need to find a better name ;)

### PR DESCRIPTION
**Pull request by andywer**
Resolves #10
@mastilver

Sorry that it took so long. But now that async testing as a blocker is out of the way I will fix the small things :)

### CODE REVIEW

**Comment by andywer** [comment]
Btw, I just called it `LeakageError` as you did in the issue.

But maybe `LeakError` sounds better?
@mjhea0 @btmills

**Comment by mjhea0** [comment]
I think I prefer LeakError

**Comment by andywer** [comment]
Posted a twitter poll: https://twitter.com/andywritescode/status/863827585301696512

That might help :)

**Comment by btmills** [comment]
Good idea with the Twitter poll - I'm a fan of `MemoryLeakError`, which looks like it's winning 🦄

(Though any of the above will work, I don't have strong feelings)

**Comment by andywer** [comment]
I think `MemoryLeakError` it is. Few participants, but a clear message 😉

bildschirmfoto 2017-05-15 um 13 45 40

**Comment by andywer** [comment]
I will go out on a limb here and say that this can be merged ^^

**Pull request merged**
